spring:
  application:
    name: Job Search

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:h2:./db/test;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

  sql:
    init:
      mode: never

  h2:
    console:
      enabled: true

  messages:
    basename: messages
    encoding: UTF-8

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: ${EMAIL_USERNAME:}
    password: ${EMAIL_PASSWORD:}