spring:
  application:
    name: Job Search

  datasource:
    url: jdbc:h2:./db/test;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

  sql:
    init:
      mode: never

  h2:
    console:
      enabled: true